from aiobaseclient.exceptions import BadRequestError

__all__ = [
    'BadRequestError',
]
