from .api_exception import ApiException


class AuthException(ApiException):
    """An exception raised when a problem occurs related to authentication"""
    pass
