
<!DOCTYPE html>

<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Relase Note for version 1.23.2.2.1 &#8212; PythonCA:Python module for EPICS CA library 1.22 ドキュメント</title>
    <link rel="stylesheet" type="text/css" href="_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="_static/alabaster.css" />
    <script data-url_root="./" id="documentation_options" src="_static/documentation_options.js"></script>
    <script src="_static/jquery.js"></script>
    <script src="_static/underscore.js"></script>
    <script src="_static/doctools.js"></script>
    <script src="_static/translations.js"></script>
    <link rel="index" title="索引" href="genindex.html" />
    <link rel="search" title="検索" href="search.html" />
   
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          

          <div class="body" role="main">
            
  <div class="section" id="relase-note-for-version-1-23-2-2-1">
<h1>Relase Note for version 1.23.2.2.1<a class="headerlink" href="#relase-note-for-version-1-23-2-2-1" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>これ以前のPython CAでWaveform レコードにputを繰り返すと、当初は正常に
動作しているが、2000-3000回程度を超えたところで、</p>
<blockquote>
<div><p>Fatal Python error: deallocating None</p>
</div></blockquote>
<p>とのエラーメッセージを残して、プロセスがクラッシュするという現象が発生することが判明した。</p>
<p>これに対応するために、<code class="xref py py-func docutils literal notranslate"><span class="pre">Py_XDECREF()</span></code> 呼び出しの際に参照回数を減らす対象のオブジェクト
が:py:class:<cite>Py_None</cite> で無いことをチェックするように _ca314.cpp を変更した。</p>
<p><code class="xref py py-class docutils literal notranslate"><span class="pre">Py_None</span></code> に対しても:py:func:<cite>Py_INCREF</cite> を呼んでおり、<code class="xref py py-class docutils literal notranslate"><span class="pre">Py_None</span></code> に対して:py:func:<cite>Py_DECREF</cite> を呼んだ場合、
いつでもクラッシュする訳ではないようなので、完全には理解できていないが、クラッシュすることは
なくなった。 <code class="xref py py-class docutils literal notranslate"><span class="pre">Py_None</span></code> に対して <code class="xref py py-func docutils literal notranslate"><span class="pre">Py_DECREF()</span></code> 呼び出しをかけようとした時にメッセージを出す様にしてもこのメッセージは表示されない。</p>
</div>


          </div>
          
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper"><div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation overview</a><ul>
  </ul></li>
</ul>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3 id="searchlabel">クイック検索</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" aria-labelledby="searchlabel" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"/>
      <input type="submit" value="検索" />
    </form>
    </div>
</div>
<script>$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;2018, Noboru Yamamoto.
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 4.5.0</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.12</a>
      
      |
      <a href="_sources/ReleaseMemo-1.23.2.2.1.rst.txt"
          rel="nofollow">Page source</a>
    </div>

    

    
  </body>
</html>